[package]
name = "odai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gluesql = { version =  "0.10.2" , features = ["sled-storage"]}
rdkafka = { version = "0.25", features = ["cmake-build"] }